Bugfix issue #69 -  Backport on 0.9
openwide-java/owsi-core-parent pull request #71
Opened 2017-02-01 14:31 UTC by julien-gonzalez

Backport of the bugfix for issue #69 on the branch OWSI-Core-0.9 for project purpose.

2017-02-01 14:59 UTC, lalmeras commented
Can you rework you commit's comment:

- to limit first line to 80 characters so that it can be kept on a unique line in history
- to add explicitly (if this is the case) that VisitFilters.java is just a backported class. Also, let me know if significant changes were needed to adapt this class to 0.9, so that we can write it down on the comment.

2017-02-01 15:00 UTC, lalmeras requested changes
Can you rework your commit's comment:

- to limit first line to 80 characters so that it can be kept on a unique line in history
- to add explicitly (if this is the case) that VisitFilters.java is just a backported class. Also, let me know if significant changes were needed to adapt this class to 0.9, so that we can write it down on the comment.

2017-02-01 15:00 UTC, lalmeras commented on owsi-core/owsi-core-components/owsi-core-component-wicket-more/src/main/java/fr/openwide/core/wicket/more/util/visit/VisitFilters.java
> +			return hasRenderedMarkup(object);
I'm not sure that renderedComponents is the better choice as it visits the component's children, so I think that you'll replace too much element in you AjaxRequestTarget ?

2017-02-01 15:00 UTC, lalmeras commented on owsi-core/owsi-core-components/owsi-core-component-wicket-more/src/main/java/fr/openwide/core/wicket/more/util/visit/VisitFilters.java
> +			return hasRenderedMarkup(object);
No, it's fine ; we don't use a visitor ; we just use visitObject method, so there is no hierarchy traversal. Fine.

2017-02-02 08:34 UTC, julien-gonzalez commented
Requested adjustments on commit message are done.

2017-02-02 09:32 UTC, lalmeras approved these changes

2017-02-02 09:37 UTC, merged